### ISSUE TITLE
Consistency checks for output

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/osm-tag-updater#2] opened 2022-11-14 10:30 UTC
Some thoughts on "managing input and output":
- [x] Different old tags can lead to the same result, but the result should not contain the same tags more than once.
_Example_ (in theory, currently not supported because `marked` isn't in the "type" list yet):
`parking:lane:right=marked`
`parking:lane:right:marked=painted_area_only`
➔
`parking:right:markings=yes`
`parking:right:markings=yes`

- [x] Different old tags can lead to different values for the same key. Always choose the more specific one (overwrite yes/no) or else print a warning in case of conflicts (probably tagging errors)?
_Example:_
`parking:lane:right=yes`
`parking:lane:right:parallel=on_street`
➔
`parking:right=yes`
`parking:right=lane`

- [x] Can attributes that are the same on both sides be grouped directly in the tool?
_Example:_
`parking:left=lane`
`parking:right=lane`
➔
`parking:both=lane`

- [x] How to deal with incorrect/inconsistent inputs?
_Example:_
`parking:condition:both=free`
`parking:condition:right=residents`

**Comment by tordans** [comment] 2022-12-09 14:02
> How to deal with incorrect/inconsistent inputs?

They show a warning, now

```
parking:lane:left=yes
parking:lane:both=no
parking:lane:right=no
parking:lane:both:fee=yes
parking:lane:left:fee=no
```

**Comment by SupaplexOSM** [comment] 2022-12-15 11:42
What about grouping same values on both sides in one key? E.g. `parking:left=lane` + `parking:right=lane` -> `parking:both=lane`. Is it complicated, too?

It happens very often - in every case the orientation is different on both sides. Because the old schema forced the mappers to use different orientation values (because the position was part of the key).

If it's work to implement this, it doesn't matter for now, but convenience would be rising significantly without manually fixing this :)

**Comment by tordans** [comment] 2022-12-16 05:50
@SupaplexOSM 

> What about grouping same values on both sides in one key?

I was hesitant to add; but since it happens often, its there now in `0.0.20`. Please test it out a bit so we can be sure not to make thinks worse … :).

**Comment by tordans** [comment] 2022-12-16 09:57
@SupaplexOSM 

> Different old tags can lead to different values for the same key. Always choose the more specific one (overwrite yes/no) or else print a warning in case of conflicts (probably tagging errors)?

The too will now clean this up…
- if a key is found twice (or more)
- remove the generic yes/no-tag of that key, if such a tag exists

Please look out for any issues caused by this.

This was the last one of the optimizations; I will close this. Lets reopen in case of issues.

**Closed as completed by tordans** 2022-12-16 09:57 UTC

**Comment by SupaplexOSM** [comment] 2022-12-16 11:17
Great! The merging of left+right=both seems to work fine, even in special cases like "parking:right:width=2" + "parking:left:width=2". I'm massively using the tool at the moment and will notice if something goes wrong. Can do some tests for edge cases, too.
